### ISSUE TITLE
mattermost_helper kernel_panic on osx catalina, mb air 2020

### ISSUE THREAD

**Issue by ludwig-gramberg** [mattermost/desktop#1286]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
mattermost crashes on catalina mb air 2020 triggering a kernel panic

**Environment**
- Operating System: Mac OS X 10.15.4
- Mattermost Desktop App version: 4.4.1
- Mattermost Server version: ???

**Steps to reproduce**
run mattermost client on mb air 2020

**Expected behavior**
the system does not crash with a kernel panic

**Observed behavior**
the system does crash with a kernel panic

```
panic(cpu 5 caller 0xffffff801564c32a): Kernel trap at 0xffffff8015b878e3, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000002298, CR3: 0x00000001df8ab1ae, CR4: 0x00000000003626e0
RAX: 0xffffff8015745270, RBX: 0x0000000000000000, RCX: 0x0000000004400000, RDX: 0x0000000000000000
RSP: 0xffffff9228513f30, RBP: 0xffffff9228513f70, RSI: 0x0000000000000000, RDI: 0x0000000000000000
R8:  0x0000000000000000, R9:  0x0000000000000000, R10: 0x0000000000000030, R11: 0xffffff9228513df0
R12: 0x0000000000000171, R13: 0xffffff8051777630, R14: 0x0000000000002298, R15: 0xffffff804d2d3520
RFL: 0x0000000000010297, RIP: 0xffffff8015b878e3, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x0000000000002298, Error code: 0x0000000000000000, Fault CPU: 0x5, PL: 0, VF: 1

Backtrace (CPU 5), Frame : Return Address
0xffffff9228513990 : 0xffffff80155215cd 
0xffffff92285139e0 : 0xffffff801565a3c5 
0xffffff9228513a20 : 0xffffff801564bf7e 
0xffffff9228513a70 : 0xffffff80154c7a40 
0xffffff9228513a90 : 0xffffff8015520c97 
0xffffff9228513b90 : 0xffffff8015521087 
0xffffff9228513be0 : 0xffffff8015cc2c7c 
0xffffff9228513c50 : 0xffffff801564c32a 
0xffffff9228513dd0 : 0xffffff801564c028 
0xffffff9228513e20 : 0xffffff80154c7a40 
0xffffff9228513e40 : 0xffffff8015b878e3 
0xffffff9228513f70 : 0xffffff8015a591fd 
0xffffff9228513fa0 : 0xffffff80154c713e 

BSD process name corresponding to current thread: Mattermost Helpe
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
19E287

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x0000000015200000
Kernel text base: 0xffffff8015400000
__HIB  text base: 0xffffff8015300000
System model name: MacBookAir9,1 (Mac-0CFF9C7C2B63DF8D)
System shutdown begun: NO

System uptime in nanoseconds: 11655995562942
last loaded kext at 11296089877064: >usb.IOUSBHostHIDDevice	1.2 (addr 0xffffff7f990de000, size 45056)
last unloaded kext at 11360108053862: >!UAudio	322.2 (addr 0xffffff7f9992b000, size 434176)
loaded kexts:
com.vmware.kext.vmioplug.18.7.0	18.7.0
com.vmware.kext.vmx86	1587.03.45
com.vmware.kext.vmnet	1587.03.45
>usb.!UHostBillboardDevice	1.0
@filesystems.smbfs	3.4.2
>!AGraphicsDevicePolicy	5.1.16
@fileutil	20.036.15
@AGDCPluginDisplayMetrics	5.1.16
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.4f6
>AGPM	111.4.4
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
>!AUpstreamUserClient	3.6.8
>pmtelemetry	1
>!A!IICLGraphics	14.0.5
@Dont_Steal_Mac_OS_X	7.0.0
>!ABacklight	180.3
>BridgeAudioCommunication	6.70.3
>!AThunderboltIP	3.1.4
>!AMCCSControl	1.11
>!ABridgeAudio!C	6.70.3
>!AHIDALSService	1
>!AGFXHDA	100.1.426
>!ATopCaseHIDEventDriver	3430.1
>!A!IPCHPMC	2.0.1
>!A!IICLLPGraphicsFramebuffer	14.0.5
>!A!ISlowAdaptiveClocking	4.0.0
>!AAVEBridge	6.1
@filesystems.autofs	3.0
@filesystems.apfs	1412.101.1
>BCMWLANFirmware4355.Hashstore	1
>BCMWLANFirmware4364.Hashstore	1
>BCMWLANFirmware4377.Hashstore	1
>!A!BModule	1
@filesystems.hfs.kext	522.100.5
@BootCache	40
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
>!AVirtIO	1.0
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!ABCMWLANBusInterfacePCIe	1
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
>usb.!UHub	1.2
>!AGraphicsControl	5.1.16
|IOAVB!F	840.3
>!ASSE	1.0
>!ABacklightExpert	1.1.0
@!AGPUWrangler	5.1.16
>!AActuatorDriver	3440.1
>X86PlatformPlugin	1.0.0
>!ASMBus!C	1.0.18d1
@plugin.IOgPTPPlugin	840.3
|IOEthernetAVB!C	1.1.0
|IONDRVSupport	575.1
>!AHS!BDriver	3430.1
>IO!BHIDDriver	7.0.4f6
>!AMultitouchDriver	3440.1
>!AInputDeviceSupport	3440.8
>!AHIDKeyboard	209
>IOPlatformPlugin!F	6.0.0d8
@!AGraphicsDeviceControl	5.1.16
|IOAccelerator!F2	438.4.5
|IOGraphics!F	575.1
|IOSlowAdaptiveClocking!F	1.0.0
@kext.triggers	1.0
>usb.cdc.ncm	5.0.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>usb.!UVHCIBCE	1.2
>usb.!UVHCI	1.2
>usb.!UVHCICommonBCE	1.0
>usb.!UVHCICommon	1.0
>!AEffaceableNOR	1.0
|IOBufferCopy!C	1.1.0
|IOBufferCopyEngine!F	1
|IONVMe!F	2.1.0
>IO!BHost!CPCIeTransport	7.0.4f6
|IO!BHost!CTransport	7.0.4f6
>!A!BDebug	1
>!AConvergedIPCOLYBTControl	1
>!A!BDebugService	1
>!AConvergedPCI	1
>!AThunderboltPCIDownAdapter	2.5.4
>!AThunderboltDPInAdapter	6.2.6
>!AThunderboltDPAdapter!F	6.2.6
>!AHPM	3.4.4
>!A!ILpssI2C!C	3.0.60
>!A!ILpssDmac	3.0.60
>!A!ILpssI2C	3.0.60
>!AThunderboltNHI	5.8.6
|IOThunderbolt!F	7.6.0
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
|IOSurface	269.11
@filesystems.hfs.encodings.kext	1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!ABCMWLANCore	1.0.0
>mDNSOffloadUserClient	1.0.1b8
>IOImageLoader	1.0.0
|IOSerial!F	11
|IO80211!FV2	1200.12.2b1
|IOSkywalk!F	1
>!AEFIRuntime	2.1
>!AMultiFunctionManager	1
>corecapture	1.0.4
>!ASMCRTC	1.0
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>!AKeyStore	2
>!UTDM	489.101.1
|IOSCSIBlockCommandsDevice	422.101.1
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|CoreAnalytics!F	1
|IOTimeSync!F	840.3
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	7.0.4f6
|IO!BPacketLogger	7.0.4f6
|IOUSBMass!SDriver	157.101.3
|IOSCSIArchitectureModel!F	422.101.1
|IO!S!F	2.1
|IOUSBHost!F	1.2
>usb.!UCommon	1.0
>!UHostMergeProperties	1.2
>!ABusPower!C	1.0
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1
```

**Possible fixes**

**Comment by Willyfrog** [comment]
Hi, thank you for the report, mind if I ask you a few questions? Feel free to contact us in the community server if any response contains any sensitive info.

 is this happening consistently?

Is there any special configuration that you have? 

Did you update recently to Catalina or the app?

Are you running as an admin or a regular user?

**Comment by ludwig-gramberg** [comment]
* it happened twice already, and without me even doing anything in the app
* what constitutes special?
* this is a new notebook i have for like 5 days, so everything is up to date and newly installed
* i'm running as a standard osx user, i guess thats an admin?

**Comment by Willyfrog** [comment]
sorry if I'm being a bit generalist, I'm trying to figure out how it is configured as I don't have any other report of people having it to crash, so I'm guessing you have something different and trying to figure out what. Do you only log into one server or use several?

do you have any logs in `~/Library/ApplicationSupport/Mattermost/` that might show more info on the crash?

**Comment by ludwig-gramberg** [comment]
I totally understand, I did not have any special config on the app. I just downloaded it, put in my credentials and that was it. 
Files in Application Support:

**uncaughtException-1588847864869.txt**:
```
Application: Mattermost 4.4.1
Platform: Darwin 19.4.0 x64
TypeError: Cannot read property 'show' of null
    at App.handleAppActivate (/Applications/Mattermost.app/Contents/Resources/app.asar/main_bundle.js:440:14)
    at App.emit (events.js:200:13)
```

other than this one file all looks "normal" to me

**Comment by Willyfrog** [comment]
i can create a patch for that exception and build a test for you if you are willing to try, but I'm shocked that an electron app gets the OS to crash completely.

I'm also wondering what makes the new macbook air especial in that regard, i'm on a macbook pro using the same 10.15.4 version.

Also, does this happen when you start the app, or after a while? if it is after a while, was the window open, minimized or closed?

**Comment by ludwig-gramberg** [comment]
- seamed random, hours after the app was started
- app was running, window was minimized
- i have vmware with kernel-extension installed (otherwise its vanilla catalina)

**Comment by ludwig-gramberg** [comment]
I can try when I dont' have to work on the notebook.
Weekend of May 16.-17.  I could install again and let it run in the background.

**Comment by Willyfrog** [comment]
contact me on mattermost's community server (either direct message to me or in the desktop channel) a little bit earlier so I can create a build for you.

I'm also seeing quite a few bug fixes on electron 6.x branch but i don't see any hard crash

**Comment by ludwig-gramberg** [comment]
ok, i will add it to my calender

**Comment by ludwig-gramberg** [comment]
i think we can close this for now, i was hit again by random crashes, I now think it was random that it happened to matter most.
its just this darn buggy catalina 10.15.4 (why did I ever update... )
