### ISSUE TITLE
Support for ARM64 Architecture

### ISSUE THREAD

**Issue by chief-wrench** [mattermost/desktop#1476]
Having just received my PinePhone (Arm64 CPU) I want to start using the native Mattermost client. 

With Apple going ARM as well now, also Electron starts supporting ARM. Will someone start porting the Mattermost client to ARM?

Being a total n00b to this topic, I can contribute nothing but ideas, unfortunately.

**Comment by shvetsnikita** [comment]
It's seems like this issue should be reopened as no Linux-compatible ARM-builds has been published on releases page.

**Comment by kkeijzer** [comment]
I agree that For PinePhone (Pro) / Pinebook (Pro) users, having an aarch64 Linux build available would definitely be very useful. Currently only amd64 and i386 builds are listed, even though aarch64 is much more commonly used than i386 is, as nearly every distribution has dropped i386 support in the last years.

**Comment by kkeijzer** [comment]
I'm trying to run the arm64 build artifact on a Pinebook Pro, and it doesn't seem to work:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /home/kevin/Downloads/mattermost-desktop-5.3.0-develop.1-linux-arm64/resources/app.asar.unpacked/node_modules/macos-notification-state/build/Release/notificationstate.node: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1810)
    at Module._extensions..node (node:internal/modules/cjs/loader:1205:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2037)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/home/kevin/Downloads/mattermost-desktop-5.3.0-develop.1-linux-arm64/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/kevin/Downloads/mattermost-desktop-5.3.0-develop.1-linux-arm64/resources/app.asar/node_modules/macos-notification-state/lib/index.js:1:34)

**Comment by devinbinnie** [comment]
Closed by https://github.com/mattermost/desktop/pull/2428
