### ISSUE TITLE
platform panic

### ISSUE THREAD

**Issue by flunda** [mattermost/desktop#156]
Hi guys,

```
Version: 3.0.0
Build Number: 3.0.2
Build Date: Tue May 17 21:26:28 UTC 2016
Build Hash: ac509b114df1c1b4b841eded74fb797805e0162d
Build Enterprise Ready: false
OS: CentOS7
```

Issue: Service frequently dying 

in /var/log/messages we see the following:

```
May 31 14:18:40 chat1 platform: [14:18:40 CEST 2016/05/31] [INFO] (github.com/mattermost/platform/utils.GetTranslationsBySystemLocale:56) Loaded system translations for 'en' from '/opt/mattermost/i18n/en.json'
May 31 14:55:35 chat1 platform: panic: runtime error: invalid memory address or nil pointer dereference
May 31 14:55:35 chat1 platform: [signal 0xb code=0x1 addr=0xd8 pc=0x5ec90c]
May 31 14:55:35 chat1 platform: goroutine 5880 [running]:
May 31 14:55:35 chat1 platform: panic(0xca20c0, 0xc82000a0a0)
May 31 14:55:35 chat1 platform: /usr/local/go/src/runtime/panic.go:481 +0x3e6
May 31 14:55:35 chat1 platform: github.com/mattermost/platform/api.sendNotifications(0xc82092e5a0, 0xc8206289a0, 0xc820a465a0, 0xc820a2a4d0, 0xc820ced960, 0xc82060a100, 0x18, 0x20)
May 31 14:55:35 chat1 platform: /var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/api/post.go:520 +0x67ec
May 31 14:55:35 chat1 platform: created by github.com/mattermost/platform/api.handlePostEventsAndForget.func1
May 31 14:55:35 chat1 platform: /var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/api/post.go:281 +0x121d
May 31 14:55:35 chat1 systemd: mattermost.service: main process exited, code=exited, status=2/INVALIDARGUMENT
May 31 14:55:35 chat1 systemd: Unit mattermost.service entered failed state.
```

please check.

**Comment by Razzeee** [comment]
This is the repo for the desktop app, not the platform. You might want to take the pr there.

**Comment by yuya-oc** [comment]
Yes, please check mattermost/platform repo.
