### ISSUE TITLE
quit unexpectitly (Render frame was disposed)

### ISSUE THREAD

**Issue by ServerMonkey** [mattermost/desktop#1888]
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

Crashes on startup with "Error: Render frame was disposed before WebFrameMain could be accessed"
Also see this (same) issue on flathub: https://github.com/flathub/com.mattermost.Desktop/issues/41

**Environment**
- Operating System: Debian 10 stable (Linux 4.19.0-18-amd64 x64), XFCE, latest upgrades (as of date of this post)
- Mattermost Desktop App (flatpak) version: 5.0.0, 5.0.1 and 5.0.2
- Mattermost Server version: does not matter in this case
- Flatpak installation steps:
`apt install -y flatpak gnome-software-plugin-flatpak && flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo`

**Steps to reproduce**
Just start Mattermost
Default flatpak start command is:
`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=mattermost-flatpak --file-forwarding com.mattermost.Desktop --enable-features=WebRTCPipeWireCapturer @@u %U @@`

I also tried it in a new VM with the same Debian settings.
Use this for testing:
```
apt update && apt upgrade
tasksel (choose xfce)
apt install -y flatpak gnome-software-plugin-flatpak && flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install mattermost
```

**Observed behavior**
I believe there seems to be some kind of race condition going on.
If I try to start Mattermost several times, after each other, I get different behavior.
Mostly I get two different error messages, and on rare-occasions (5% of the time) it actually starts correctly!
The different error messages I get are:

```
Application: Mattermost 5.0.2
Platform: Linux 4.19.0-18-amd64 x64
Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (electron/js2c/browser_init.js:165:413)
    at Object.b.send (electron/js2c/browser_init.js:161:2492)
    at ViewManager.fadeLoadingScreen (/app/main/resources/app.asar/index.js:60982:40)
    at ViewManager.setServerInitialized (/app/main/resources/app.asar/index.js:60999:16)
    at IpcMainImpl.handleReactAppInitialized (/app/main/resources/app.asar/index.js:60250:24)
    at IpcMainImpl.emit (events.js:376:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9959)
    at Object.emit (events.js:376:20)
```

OR:

```
Application: Mattermost 5.0.2
Platform: Linux 4.19.0-18-amd64 x64
Error: Render frame was disposed before WebFrameMain could be accessed
    at Object.n.send (electron/js2c/browser_init.js:165:413)
    at Object.b.send (electron/js2c/browser_init.js:161:2492)
    at TeamDropdownView.updateDropdown (/app/main/resources/app.asar/index.js:65576:29)
    at EventEmitter.<anonymous> (/app/main/resources/app.asar/index.js:65567:12)
    at EventEmitter.emit (events.js:376:20)
    at emitDropdown (/app/main/resources/app.asar/index.js:64595:18)
    at emitStatus (/app/main/resources/app.asar/index.js:64604:3)
    at emitMentions (/app/main/resources/app.asar/index.js:64583:3)
    at setSessionExpired (/app/main/resources/app.asar/index.js:64718:3)
    at IpcMainImpl.<anonymous> (/app/main/resources/app.asar/index.js:64724:3)
```

**Comment by devinbinnie** [comment]
Hi @ServerMonkey, this is fixed in this PR: https://github.com/mattermost/desktop/pull/1886
