### ISSUE TITLE
crash: Internal error: Maximum call stack size exceeded in 5.1.0-rc.2-19360

### ISSUE THREAD

**Issue by kenyon** [mattermost/desktop#2098]
I confirm (by marking "x" in the [ ] below: [x]):

- [ ] I have confirmed this is an issue on the newest beta build [available here](https://github.com/mattermost/desktop/tags)
- [x] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
`mattermost-desktop` version 5.1.0-rc.2-19360 on Ubuntu 18.04 amd64 crashes with the following error:

```
Internal error: Maximum call stack size exceeded
  at BrowserWindow.handle (/opt/Mattermost/resources/app.asar/index.js:74560:21)
  at BrowserWindow.emit (node:events:402:35)
  at BrowserWindow.handle (/opt/Mattermost/resources/app.asar/index.js:74560:21)
  at BrowserWindow.emit (node:events:402:35)
  at BrowserWindow.handle (/opt/Mattermost/resources/app.asar/index.js:74560:21)
  at BrowserWindow.emit (node:events:402:35)
  at BrowserWindow.handle (/opt/Mattermost/resources/app.asar/index.js:74560:21)
  at BrowserWindow.emit (node:events:402:35)
  at BrowserWindow.handle (/opt/Mattermost/resources/app.asar/index.js:74560:21)
  at BrowserWindow.emit (node:events:402:35)
```

**Environment**
- Operating System: Ubuntu 18.04
- Mattermost Desktop App version: 5.1.0-rc.2-19360
- Mattermost Server version: 6.5.0 Enterprise Edition

**Steps to reproduce**
Unknown.

**Expected behavior**
No crashes.

**Observed behavior**
Crash (segfault, SIGSEGV, signal 11, core dumped).

I have around 150 workstations running 5.1.0-rc.2, 5.1.0-rc.3, or 5.1.0-rc.4, mostly (137 of them) 5.1.0-rc.2, on either Ubuntu 18.04 or 20.04. All installed from the `deb` package. I've received three reports of the above crash from users running 5.1.0-rc.2 on Ubuntu 18.04. The core dump appears to be useless ("no symbol table info available"). `mattermost-desktop` 5.0.4-17219 does not have this crash.

**Comment by amyblais** [comment]
@devinbinnie Is there enough information to investigate this?
