### ISSUE TITLE
Unable to set default server

### ISSUE THREAD

**Issue by JmzTaylor** [mattermost/desktop#2223]
```
// Copyright (c) 2015-2016 Yuya Ochiai
// Copyright (c) 2016-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import {BuildConfig} from 'types/config';

// For detailed guides, please refer to https://docs.mattermost.com/deployment/desktop-app-deployment.html

/**
 * Build-time configuration. End-users can't change these parameters.
 * @prop {Object[]} defaultTeams
 * @prop {string} defaultTeams[].name - The tab name for default team.
 * @prop {string} defaultTeams[].url - The URL for default team.
 * @prop {string} defaultTeams[].order - Sort order for team tabs (0, 1, 2)
 * @prop {string} helpLink - The URL for "Help->Learn More..." menu item.
 *                           If null is specified, the menu disappears.
 * @prop {boolean} enableServerManagement - Whether users can edit servers configuration.
 *                                          Specify at least one server for "defaultTeams"
 *                                          when "enableServerManagement is set to false
 * @prop {[]} managedResources - Defines which paths are managed
 */
const buildConfig: BuildConfig = {
    defaultTeams: [/*
    {
      name: 'server_name',
      url: 'https://server_url'
    }
  */],
    helpLink: 'https://docs.mattermost.com/messaging/managing-desktop-app-servers.html',
    enableServerManagement: false,
    enableAutoUpdater: true,
    managedResources: ['trusted'],
};

export default buildConfig;

```

When compiling with this set, the resulting binary ignores it.  In addition, when prompted for server name and URL it infinitely loops back to add server dialog.  No changes have been done to repo except this.  And this happens on all platforms; windows, linux and mac.

**Comment by devinbinnie** [comment]
@JmzTaylor I'm not seeing any issues on my end. Is the config you've posted exactly what you're using? Because currently the server added there is commented out.

```
defaultTeams: [/* <-------
    {
      name: 'server_name',
      url: 'https://server_url'
    }
  */]
```

**Comment by JmzTaylor** [comment]
> @JmzTaylor I'm not seeing any issues on my end. Is the config you've posted exactly what you're using? Because currently the server added there is commented out.
> 
> ```
> defaultTeams: [/* <-------
>     {
>       name: 'server_name',
>       url: 'https://server_url'
>     }
>   */]
> ```

Yup thats my fault.  didn't see that at the end of the line.  Sorry about that.

**Comment by JmzTaylor** [comment]
So, I removed the comments, added order and tests are failing now.

```
Summary of all failing tests
 FAIL  src/main/views/viewManager.test.js
  ● Test suite failed to run

    TypeError: (0 , _TabView.getDefaultTeamWithTabsFromTeam) is not a function

      88 |         this.predefinedTeams = [];
      89 |         if (buildConfig.defaultTeams) {
    > 90 |             this.predefinedTeams.push(...buildConfig.defaultTeams.map((team) => getDefaultTeamWithTabsFromTeam(team)));
         |                                                                                 ^
      91 |         }
      92 |         try {
      93 |             this.useNativeWindow = os.platform() === 'win32' && !Utils.isVersionGreaterThanOrEqualTo(os.release(), '6.2');

      at map (src/common/config/index.ts:90:81)
          at Array.map (<anonymous>)
      at new Config (src/common/config/index.ts:90:67)
      at Object.<anonymous> (src/common/config/index.ts:624:16)
      at Object.<anonymous> (src/main/views/viewManager.ts:25:1)

```

config:

```
const buildConfig: BuildConfig = {
    defaultTeams: [
    {
      name: 'server_name',
      url: 'https://server_url',
      order: 1
    }
    ],
    helpLink: 'https://docs.mattermost.com/messaging/managing-desktop-app-servers.html',
    enableServerManagement: false,
    enableAutoUpdater: true,
    managedResources: ['trusted'],
};

export default buildConfig;
```

**Comment by devinbinnie** [comment]
@JmzTaylor Is having the tests passing when you add a team to the build config something you'll need as part of a CI pipeline you're working on? The tests aren't really designed to run when the build config is changed, as it's provided so that users/developers can add default servers and set other options at build time.

**Comment by JmzTaylor** [comment]
> @JmzTaylor Is having the tests passing when you add a team to the build config something you'll need as part of a CI pipeline you're working on? The tests aren't really designed to run when the build config is changed, as it's provided so that users/developers can add default servers and set other options at build time.

Not really.  I can just ignore them.  I was trying to stay inline with upstream as much as possible to prevent too large of a delta.  If that is the solution then I have no problem with that.
