### ISSUE TITLE
Title bar menus disappear after server switching

### ISSUE THREAD

**Issue by MFHava** [mattermost/desktop#2388]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10 22H2 (19045.2130)
- Mattermost Desktop App version: 5.2.1

**Steps to reproduce**
1) Switch between server instances in the desktop client

**Expected behavior**
The title bar menus stay.

**Observed behavior**
The title bar menus disappear, and the title bar becomes inactive.

Before:
![image](https://user-images.githubusercontent.com/17790925/202042364-e71ab9c8-0323-43f3-a90c-fc70ced0c237.png)
After:
![image](https://user-images.githubusercontent.com/17790925/202042422-bf9f7f08-e5d6-4e52-b8c0-44484c867fb2.png)

**Possible fixes**

**Comment by devinbinnie** [comment]
@MFHava None of our team is able to reproduce this. Is this consistently reproducing for you?

If so, before the white bar shows up can you go to View > Developer Tools for Application Wrapper, then reproduce the issue and post the log for us? Thanks!

**Comment by MFHava** [comment]
It's consistent - and happens on two independent systems for me.
Console log right after switching:

`
Starting Mattermost v5.2.1
index_bundle.js:5515 SyntaxError: Invalid regular expression: /ISO C++___TAB_[A-Z]+/: Nothing to repeat (at index_bundle.js:8910:46)
    at String.match (<anonymous>)
    at index_bundle.js:8910:46
    at Array.reduce (<anonymous>)
    at MainPage.render (index_bundle.js:8908:69)
    at gi (index_bundle.js:4822:76)
    at fi (index_bundle.js:4813:10)
    at Rj (index_bundle.js:7129:86)
    at Qj (index_bundle.js:6593:11)
    at Kj (index_bundle.js:6585:27)
    at yj (index_bundle.js:6328:7)
Ci @ index_bundle.js:5515
Xi.c.callback @ index_bundle.js:6019
Cg @ index_bundle.js:3617
Ji @ index_bundle.js:5639
Sj @ index_bundle.js:6840
exports.unstable_runWithPriority @ index_bundle.js:8137
cg @ index_bundle.js:3329
Jj @ index_bundle.js:6647
yj @ index_bundle.js:6342
(anonymous) @ index_bundle.js:3363
exports.unstable_runWithPriority @ index_bundle.js:8137
cg @ index_bundle.js:3329
fg @ index_bundle.js:3359
gg @ index_bundle.js:3349
Ig @ index_bundle.js:6129
enqueueSetState @ index_bundle.js:3646
F.setState @ index_bundle.js:89
(anonymous) @ index_bundle.js:8714
(anonymous) @ VM5:313
emit @ VM4 sandbox_bundle:112
onMessage @ VM4 sandbox_bundle:37
VM5:313 Uncaught Error: Invalid regular expression: /ISO C++___TAB_[A-Z]+/: Nothing to repeat
    at EventEmitter.<anonymous> (<anonymous>:313:80)
    at EventEmitter.emit (VM4 sandbox_bundle:112:3752)
    at Object.onMessage (VM4 sandbox_bundle:37:765)
`

**Comment by MFHava** [comment]
I'm not sure what in the server name "ISO C++" specifically triggers the problem, but changing it to something without space and plus fixes the issue apparently...
