### ISSUE TITLE
[Crash]: Clicking on any link after closing large calls window

### ISSUE THREAD

**Issue by pampersrocker** [mattermost/desktop#2646]
### Before you file a crash report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.3.0 [commit: 595f0ab ]

### Operating System

Windows 11 x64

### Mattermost Server Version

7.7.1

### What type of crash did you experience?

Uncaught exception (I saw a dialog pop up that said "The Mattermost app quit unexpectedly")

### Crash report details

```shell
Application: Mattermost 5.3.0 [commit: 595f0ab
]
Platform: Windows_NT 10.0.22621 x64
TypeError: Object has been destroyed
    at CallsWidgetWindow.getPopOutWebContentsId (C:\Users\Marvin\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:77152:101)
    at WindowManager.getServerURLFromWebContentsId (C:\Users\Marvin\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:46740:120)
    at EventEmitter._windowOpenHandler (C:\Users\Marvin\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:53024:50)
    at _._callWindowOpenHandler (node:electron/js2c/browser_init:2:78685)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:83444)
    at EventEmitter.emit (node:events:513:28)
```

### Additional Information

This is caused in combination with the mattermost calls plugin and the unwanted pre-release of the 5.3.0 application.
When opening and closing the Large Window for calls (where screensharing happen) and closing that view again. After that clicking on any link (such as settings, system console, or just a link posted in the chat) the posted error occurs and the application needs to restart.

Not sure if this is a bug specific to calls, but since this is related to the new extra windows, I am reporting this here.
I am guessing the object destroyed is that large window.

**Comment by pampersrocker** [comment]
I just noticed the callstack ending in the calls plugin, so moving it there
