### ISSUE TITLE
[Bug]: I am not able to developer setup locally on my laptop

### ISSUE THREAD

**Issue by kondareddy** [mattermost/desktop#2684]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.4.0-develop.1

### Operating System

Windows 10 x64

### Steps to reproduce

**1. I am trying to develop setup for desktop, but struck with multiple issues. as per this documentation** https://developers.mattermost.com/contribute/more-info/desktop/developer-setup/

npm i is always failing with some exception - attached log file

**2. build and cli commands also not working**

C:\Jio\Repo\mattermost-desktop>npm run clean
'rm' is not recognized as an internal or external command,
operable program or batch file.

**3. How do I change .pfx file to our's**

### Expected behavior

Should be able setup locally and run desktop on windows

### Observed behavior

Not able to setup/configure

### Log Output

```shell
3665 timing reify:rollback:createSparse Completed in 54927ms
3666 timing reify:rollback:retireShallow Completed in 16ms
3667 timing command:i Completed in 263238ms
3668 verbose stack Error: command failed
3668 verbose stack     at ChildProcess.<anonymous> (C:\Users\konda2.reddy\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
3668 verbose stack     at ChildProcess.emit (node:events:513:28)
3668 verbose stack     at maybeClose (node:internal/child_process:1091:16)
3668 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
3669 verbose pkgid windows-focus-assist@1.3.0
3670 verbose cwd C:\Jio\Repo\mattermost-desktop
3671 verbose Windows_NT 10.0.19043
3672 verbose node v18.16.0
3673 verbose npm  v9.4.1
3674 error code 1
3675 error path C:\Jio\Repo\mattermost-desktop\node_modules\windows-focus-assist
3676 error command failed
3677 error command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
3678 error Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
3678 error
3678 error   64 bit Processing ..\lib\quiethours.idl
3678 error   quiethours.idl
3678 error   64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.idl
3678 error   oaidl.idl
3678 error   64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\objidl.idl
3678 error   objidl.idl
3678 error   64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\unknwn.idl
3678 error   unknwn.idl
3678 error   64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\wtypes.idl
3678 error   wtypes.idl
3678 error   64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\wtypesbase.idl
3678 error   wtypesbase.idl
3678 error   64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\basetsd.h
3678 error   basetsd.h
3678 error   64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\guiddef.h
3678 error   guiddef.h
3678 error   64 bit Processing C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.acf
3678 error   oaidl.acf
3678 error   focus-assist.cc
3678 error C:\Jio\Repo\mattermost-desktop\node_modules\windows-focus-assist\lib\focus-assist.cc(154,5): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [C:\Jio\Repo\mattermost-desktop\node_modules\windows-focus-assist\build\focusassist.vcxproj]
3678 error   quiethours_i.c
3678 error   win_delay_load_hook.cc
3678 error LINK : fatal error LNK1104: cannot open file 'atls.lib' [C:\Jio\Repo\mattermost-desktop\node_modules\windows-focus-assist\build\focusassist.vcxproj]
3679 error gyp info it worked if it ends with ok
3679 error gyp info using node-gyp@9.3.0
3679 error gyp info using node@18.16.0 | win32 | x64
3679 error gyp info find Python using Python version 3.11.3 found at "C:\Python311\python.exe"
3679 error gyp info find VS using VS2022 (17.5.33424.131) found at:
3679 error gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
3679 error gyp info find VS run with --verbose for detailed information
3679 error gyp info spawn C:\Python311\python.exe
3679 error gyp info spawn args [
3679 error gyp info spawn args   'C:\\Jio\\Repo\\mattermost-desktop\\node_modules\\node-gyp\\gyp\\gyp_main.py',
3679 error gyp info spawn args   'binding.gyp',
3679 error gyp info spawn args   '-f',
3679 error gyp info spawn args   'msvs',
3679 error gyp info spawn args   '-I',
3679 error gyp info spawn args   'C:\\Jio\\Repo\\mattermost-desktop\\node_modules\\windows-focus-assist\\build\\config.gypi',
3679 error gyp info spawn args   '-I',
3679 error gyp info spawn args   'C:\\Jio\\Repo\\mattermost-desktop\\node_modules\\node-gyp\\addon.gypi',
3679 error gyp info spawn args   '-I',
3679 error gyp info spawn args   'C:\\Users\\konda2.reddy\\AppData\\Local\\node-gyp\\Cache\\18.16.0\\include\\node\\common.gypi',
3679 error gyp info spawn args   '-Dlibrary=shared_library',
3679 error gyp info spawn args   '-Dvisibility=default',
3679 error gyp info spawn args   '-Dnode_root_dir=C:\\Users\\konda2.reddy\\AppData\\Local\\node-gyp\\Cache\\18.16.0',
3679 error gyp info spawn args   '-Dnode_gyp_dir=C:\\Jio\\Repo\\mattermost-desktop\\node_modules\\node-gyp',
3679 error gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\konda2.reddy\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.16.0\\\\<(target_arch)\\\\node.lib',
3679 error gyp info spawn args   '-Dmodule_root_dir=C:\\Jio\\Repo\\mattermost-desktop\\node_modules\\windows-focus-assist',
3679 error gyp info spawn args   '-Dnode_engine=v8',
3679 error gyp info spawn args   '--depth=.',
3679 error gyp info spawn args   '--no-parallel',
3679 error gyp info spawn args   '--generator-output',
3679 error gyp info spawn args   'C:\\Jio\\Repo\\mattermost-desktop\\node_modules\\windows-focus-assist\\build',
3679 error gyp info spawn args   '-Goutput_dir=.'
3679 error gyp info spawn args ]
3679 error gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe
3679 error gyp info spawn args [
3679 error gyp info spawn args   'build/binding.sln',
3679 error gyp info spawn args   '/clp:Verbosity=minimal',
3679 error gyp info spawn args   '/nologo',
3679 error gyp info spawn args   '/p:Configuration=Release;Platform=x64'
3679 error gyp info spawn args ]
3679 error gyp ERR! build error 
3679 error gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
3679 error gyp ERR! stack     at ChildProcess.onExit (C:\Jio\Repo\mattermost-desktop\node_modules\node-gyp\lib\build.js:203:23)
3679 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
3679 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
3679 error gyp ERR! System Windows_NT 10.0.19043
3679 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Jio\\Repo\\mattermost-desktop\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
3679 error gyp ERR! cwd C:\Jio\Repo\mattermost-desktop\node_modules\windows-focus-assist
3679 error gyp ERR! node -v v18.16.0
3679 error gyp ERR! node-gyp -v v9.3.0
3679 error gyp ERR! not ok
3680 verbose exit 1
3681 timing npm Completed in 263433ms
3682 verbose unfinished npm timer reify 1681985551322
3683 verbose unfinished npm timer reify:build 1681985737013
3684 verbose unfinished npm timer build 1681985737017
3685 verbose unfinished npm timer build:deps 1681985737018
3686 verbose unfinished npm timer build:run:install 1681985739011
3687 verbose unfinished npm timer build:run:install:node_modules/windows-focus-assist 1681985739061
3688 verbose code 1
3689 error A complete log of this run can be found in:
3689 error     C:\Users\konda2.reddy\AppData\Local\npm-cache\_logs\2023-04-20T10_12_31_159Z-debug-0.log
```

### Additional Information

dummpy

**Comment by kondareddy** [comment]
Looks like "node_modules/windows-focus-assist" folder not created , not sure how to get created required files

**Comment by devinbinnie** [comment]
@kondareddy I'm closing this ticket as this is a troubleshooting question. Feel free to reach out on Mattermost Community here and we can help you out: https://community.mattermost.com/core/channels/desktop-app

**Comment by kondareddy** [comment]
refer this for solution - https://community.mattermost.com/core/threads/isk4p8zzjtye9mw4eqdrx16bky
