### ISSUE TITLE
[Bug]: Updater not working

### ISSUE THREAD

**Issue by cwdtle** [mattermost/desktop#2762]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.3.1

### Operating System

Windows 11 x64

### Mattermost Server Version

7.10.2

### Steps to reproduce

Accept the download recommendation in the Windows Client by clicking on it.

### Expected behavior

The download succeeds and the update starts or at least gives the opportunity to start the update.

### Observed behavior

Download stays at 224/224 MB and no further actions occur.

### Log Output

```shell
[2023-06-20 07:55:47.505] [info]  Checking for update
[2023-06-20 07:55:48.051] [info]  Found version 5.4.0 (url: 5.4.0/mattermost-desktop-setup-5.4.0-win.exe)
[2023-06-20 07:55:48.058] [info]  [Mattermost] available version 5.4.0
[2023-06-20 08:33:12.953] [info]  Downloading update from 5.4.0/mattermost-desktop-setup-5.4.0-win.exe
[2023-06-20 08:33:12.957] [info]  Download block maps (old: "https://releases.mattermost.com/desktop/5.3.1/mattermost-desktop-setup-5.3.1-win.exe.blockmap", new: https://releases.mattermost.com/desktop/5.4.0/mattermost-desktop-setup-5.4.0-win.exe.blockmap)
[2023-06-20 08:33:13.516] [error] Cannot download differentially, fallback to full download: Error: Cannot download "https://releases.mattermost.com/desktop/5.3.1/mattermost-desktop-setup-5.3.1-win.exe.blockmap", status 403: 
    at ClientRequest.<anonymous> (C:\Users\XXX\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:57659:26)
    at ClientRequest.emit (node:events:513:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49128)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
[2023-06-20 08:33:35.718] [error] Error: Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:768:9)
    at Object.execFile (node:child_process:351:17)
    at t.<computed> [as execFile] (node:electron/js2c/asar_bundle:2:2218)
    at C:\Users\XXX\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:71500:21
    at new Promise (<anonymous>)
    at Object.verifySignature (C:\Users\XXX\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:71478:10)
    at NsisUpdater.verifySignature (C:\Users\XXX\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:71262:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.task (C:\Users\XXX\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:71211:45)
[2023-06-20 08:33:35.719] [error] [Mattermost] There was an error while trying to update: Error: spawn UNKNOWN
```

**Comment by devinbinnie** [comment]
@cwdtle Updater should be working fine, are you running in a managed environment? Looks like you might be having trouble running the downloaded file from the `spawn UNKNOWN` error.

**Comment by cwdtle** [comment]
@devinbinnie No, there's no managed environment.
The client is initially "manually" installed by the user itself or an admin-user (local or domain-admin).
Either way the updater is not working.
Manually downloading and installing the current Client-App is working just fine with either user or admin.

**Comment by devinbinnie** [comment]
@cwdtle Are there any group policies blocking the use of the Command Prompt? That's another likely cause of the `spawn UNKNOWN` error.

**Comment by devinbinnie** [comment]
@cwdtle It's possible the library needs PowerShell as well, I'd see if you can test on a non-restricted environment, as I believe the auto-updater relies on those permissions being available.

**Comment by cwdtle** [comment]
@devinbinnie yep, blocking PowerShell ist causing the Problem.
Well, i guess no Updating via App for us then ;)
Thank you

**Comment by devinbinnie** [comment]
> @devinbinnie yep, blocking PowerShell ist causing the Problem. Well, i guess no Updating via App for us then ;) Thank you

You can always do it manually ;)
