### ISSUE TITLE
[Bug]: Correct server URL appears to be invalid Mattermost server URL

### ISSUE THREAD

**Issue by christianhueserhzdr** [mattermost/desktop#2810]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.4.0

### Operating System

Ubuntu Linux 22.04 LTS x64

### Mattermost Server Version

7.10.4

### Steps to reproduce

1. Enter Mattermost server URL when connecting to new Mattermost service.
2. Message appears on the screen: `The server URL provided does not appear to point to a valid Mattermost server. Please verify the URL and check your connection.`

### Expected behavior

Correct Mattermost server URL can be entered without a warning being displayed.

### Observed behavior

When entering Mattermost server URL warning is displayed:  `The server URL provided does not appear to point to a valid Mattermost server. Please verify the URL and check your connection.` 

### Log Output

```shell
No log
```

**Comment by christianhueserhzdr** [comment]
This bug seems to be related to issue #2772 but plugins are not disabled.

**Comment by devinbinnie** [comment]
@christianhueserhzdr Can you turn on Debug logging and provide the output of what is shown in the log when you try to enter the URL? If there is sensitive data in there, you can feel free to DM me the output on https://community.mattermost.com @devinbinnie

**Comment by christianhueserhzdr** [comment]
Dear Devin @devinbinnie, thank you very much for your response. I checked the Mattermost Desktop App in version 5.5.1 with a Mattermost server version 7.10.5 and this message is not displayed anymore if the correct server URL is entered. I close this issue now.

**Comment by JosephNewhall** [comment]
I am getting the same message, just updated to 7.1.9 and it works via the website but not in the desktop client:

Mattermost TEAM Version: 7.1.9
Database Schema Version: 95
Database: mysql

Window client error log:

Application: Mattermost 5.5.1 [commit: db8645b]
Platform: Windows_NT 10.0.19045 x64
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:560:13)
    at get url [as url] (C:\Users\joe.BSS.000\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:57333:12)
    at MattermostBrowserView.load (C:\Users\joe.BSS.000\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:85532:29)
    at ViewManager.makeView (C:\Users\joe.BSS.000\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:84336:19)
    at ServerManager.<anonymous> (C:\Users\joe.BSS.000\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:84504:35)
    at ServerManager.emit (node:events:525:35)
    at ServerManager.persistServers (C:\Users\joe.BSS.000\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:56333:12)
    at ServerManager.updateLastActive (C:\Users\joe.BSS.000\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:56263:12)
    at ServerViewState.updateCurrentView (C:\Users\joe.BSS.000\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:84889:30)
