### ISSUE TITLE
[Bug]: Mattermost window keeps resizing each time after relaunch

### ISSUE THREAD

**Issue by Izaya21** [mattermost/desktop#3067]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.8.1

### Operating System

Windows 11

### Mattermost Server Version

9.8.1

### Steps to reproduce

Restart Mattermost

### Expected behavior

Maintains the resized window

### Observed behavior

Windows goes smaller each time the app is restarted

### Log Output

```shell
[2024-06-14 05:05:39.980] [error] Logger Log level set to: info
[2024-06-14 05:05:40.076] [warn]  [App.Initialize] Current working directory is C:\Windows\System32, changing into C:\Users\User\AppData\Local\Programs\mattermost-desktop
[2024-06-14 05:05:40.110] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 05:05:40.133] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 05:05:40.246] [info]  [ServerDropdownView] init
[2024-06-14 05:05:40.271] [info]  [i18nManager] Set new language pl
[2024-06-14 05:05:40.284] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 05:05:40.312] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 05:05:40.762] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 05:05:45.226] [info]  [UpdateManager] Checking for update
[2024-06-14 05:05:45.895] [info]  [UpdateManager] Found version 5.8.1 (url: 5.8.1/mattermost-desktop-setup-5.8.1-win.exe)
[2024-06-14 05:05:45.896] [info]  [UpdateManager] New version available: 5.8.1
[2024-06-14 05:05:48.070] [info]  [UpdateManager] Downloading update from 5.8.1/mattermost-desktop-setup-5.8.1-win.exe
[2024-06-14 05:05:48.075] [info]  [UpdateManager] Cached update sha512 checksum doesn't match the latest available update. New update must be downloaded. Cached: JN2VASptdWiUrL2uVTmF8v37tiKGGXogQ9XN4WEy/DbC5/axD4Zxpb+BDjuYbZqP8uiXHyATTPUVx2Wekgvf0g==, expected: WN50bN8A+5ubG+MyFpmkyJc/GFItGwVItFO3p0hrp//45KkDn0+4AXq4iC7loMr6Ab64KY2vGRFRHsY/S4O88w==. Directory for cached update will be cleaned
[2024-06-14 05:05:48.078] [info]  [UpdateManager] Download block maps (old: "https://releases.mattermost.com/desktop/5.8.0/mattermost-desktop-setup-5.8.0-win.exe.blockmap", new: https://releases.mattermost.com/desktop/5.8.1/mattermost-desktop-setup-5.8.1-win.exe.blockmap)
[2024-06-14 05:05:48.671] [info]  [UpdateManager] File has 980 changed blocks
[2024-06-14 05:05:48.679] [info]  [UpdateManager] Full: 238,004 KB, To download: 20,562.07 KB (9%)
[2024-06-14 05:05:51.066] [error] [UpdateManager] Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected WN50bN8A+5ubG+MyFpmkyJc/GFItGwVItFO3p0hrp//45KkDn0+4AXq4iC7loMr6Ab64KY2vGRFRHsY/S4O88w==, got x7Q0seWiAZsP7K7crh0sA3SU3O/7UVnrf6p9aXjyM+o7KTP+CmEiqLsM1/ON9SWv71hp4nJn/qh3EF5WcypLbQ==
    at t.newError (C:\Users\User\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:881006)
    at w.validate (C:\Users\User\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:877330)
    at WriteStream.<anonymous> (C:\Users\User\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:944607)
    at WriteStream.emit (node:events:514:28)
    at emitCloseNT (node:internal/streams/destroy:132:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
[2024-06-14 05:06:03.367] [info]  [UpdateManager] New version 5.8.1 has been downloaded to C:\Users\User\AppData\Local\mattermost-desktop-updater\pending\mattermost-desktop-setup-5.8.1-win.exe
[2024-06-14 05:06:03.369] [info]  [UpdateManager] Downloaded version 5.8.1
[2024-06-14 05:06:06.139] [info]  [UpdateManager] Install on explicit quitAndInstall
[2024-06-14 05:06:06.139] [info]  [UpdateManager] Install: isSilent: false, isForceRunAfter: true
[2024-06-14 05:06:06.139] [info]  [UpdateManager] Executing: C:\Users\User\AppData\Local\mattermost-desktop-updater\pending\mattermost-desktop-setup-5.8.1-win.exe with args: --updated,--force-run
[2024-06-14 05:06:11.146] [info]  [UpdateManager] Install on explicit quitAndInstall
[2024-06-14 05:06:11.146] [warn]  [UpdateManager] install call ignored: quitAndInstallCalled is set to true
[2024-06-14 05:06:11.158] [info]  [UpdateManager] Auto install update on quit
[2024-06-14 05:06:11.158] [info]  [UpdateManager] Install: isSilent: true, isForceRunAfter: false
[2024-06-14 05:06:11.158] [info]  [UpdateManager] Executing: C:\Users\User\AppData\Local\mattermost-desktop-updater\pending\mattermost-desktop-setup-5.8.1-win.exe with args: --updated,/S
[2024-06-14 05:06:18.863] [error] Logger Log level set to: info
[2024-06-14 05:06:19.026] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 05:06:19.052] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 05:06:19.178] [info]  [ServerDropdownView] init
[2024-06-14 05:06:19.222] [info]  [i18nManager] Set new language pl
[2024-06-14 05:06:19.234] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 05:06:19.264] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 05:06:19.284] [error] [App.Utils] clearAppCache TypeError: Object has been destroyed
[2024-06-14 05:06:20.270] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 05:06:24.156] [info]  [UpdateManager] Checking for update
[2024-06-14 05:06:24.751] [info]  [UpdateManager] Update for version 5.8.1 is not available (latest version: 5.8.1, downgrade is disallowed).
[2024-06-14 06:06:23.699] [info]  [UpdateManager] Checking for update
[2024-06-14 06:06:24.295] [info]  [UpdateManager] Update for version 5.8.1 is not available (latest version: 5.8.1, downgrade is disallowed).
[2024-06-14 06:23:09.160] [error] Logger Log level set to: info
[2024-06-14 06:23:09.289] [warn]  [App.Initialize] Current working directory is C:\Windows\system32, changing into C:\Users\User\AppData\Local\Programs\mattermost-desktop
[2024-06-14 06:23:09.353] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:23:09.386] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:23:09.537] [info]  [ServerDropdownView] init
[2024-06-14 06:23:09.592] [info]  [i18nManager] Set new language pl
[2024-06-14 06:23:09.605] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:23:09.638] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:23:10.090] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:23:14.517] [info]  [UpdateManager] Checking for update
[2024-06-14 06:23:15.105] [info]  [UpdateManager] Update for version 5.8.1 is not available (latest version: 5.8.1, downgrade is disallowed).
[2024-06-14 06:23:40.441] [error] Logger Log level set to: info
[2024-06-14 06:23:40.555] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:23:40.580] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:23:40.684] [info]  [ServerDropdownView] init
[2024-06-14 06:23:40.708] [info]  [i18nManager] Set new language pl
[2024-06-14 06:23:40.720] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:23:40.740] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:23:41.067] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:23:45.666] [info]  [UpdateManager] Checking for update
[2024-06-14 06:23:45.916] [info]  [UpdateManager] Update for version 5.8.1 is not available (latest version: 5.8.1, downgrade is disallowed).
[2024-06-14 06:23:58.981] [error] Logger Log level set to: info
[2024-06-14 06:23:59.124] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:23:59.148] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:23:59.241] [info]  [ServerDropdownView] init
[2024-06-14 06:23:59.279] [info]  [i18nManager] Set new language pl
[2024-06-14 06:23:59.291] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:23:59.311] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:23:59.648] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:24:04.233] [info]  [UpdateManager] Checking for update
[2024-06-14 06:24:04.788] [info]  [UpdateManager] Update for version 5.8.1 is not available (latest version: 5.8.1, downgrade is disallowed).
[2024-06-14 06:25:39.683] [error] Logger Log level set to: info
[2024-06-14 06:25:39.800] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:25:39.825] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:25:39.937] [info]  [ServerDropdownView] init
[2024-06-14 06:25:39.961] [info]  [i18nManager] Set new language pl
[2024-06-14 06:25:39.974] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:25:39.994] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:25:40.312] [info]  [App.Config] config.autostart has been configured: true
[2024-06-14 06:25:44.916] [info]  [UpdateManager] Checking for update
[2024-06-14 06:25:45.491] [info]  [UpdateManager] Update for version 5.8.1 is not available (latest version: 5.8.1, downgrade is disallowed).
```

### Additional Information

Problem not occurred in version 5.8.0

**Comment by devinbinnie** [comment]
Created ticket: https://mattermost.atlassian.net/browse/MM-58780
