### ISSUE TITLE
[Bug]: Window can not be moved after startup

### ISSUE THREAD

**Issue by jpk6789** [mattermost/desktop#3088]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.8.1

### Operating System

Windows 10 x64

### Mattermost Server Version

9.1.2

### Steps to reproduce

1. Start Mattermost desktop application and open the window
2. Set the window to full-screen mode
3. Exit the desktop app completely
4. Start Mattermost desktop application and open the window
5. Try to grab the window and move it to another screen
6. Try to move the window with Windows Key + left / right

### Expected behavior

The app should change to window mode and be movable with the mouse / moves to the arrangement defined by the Windows + left / right keys

### Observed behavior

The window is not movable at all. Only after setting it once to window mode, it is movable afterwards even if you then set it to full-screen mode again. However, if the window is off-screen (see #3087) you can not move the window into the accessible desktop area.

### Log Output

```shell
Same as in #3087:

[2024-07-11 10:44:41.914] [error] Logger Log level set to: info
[2024-07-11 10:44:42.129] [info]  [App.Config] config.autostart has been configured: true
[2024-07-11 10:44:42.206] [info]  [App.Config] config.autostart has been configured: true
[2024-07-11 10:44:42.429] [info]  [ServerDropdownView] init
[2024-07-11 10:44:42.496] [info]  [i18nManager] Set new language de
[2024-07-11 10:44:42.528] [info]  [App.Config] config.autostart has been configured: true
[2024-07-11 10:44:42.573] [info]  [App.Config] config.autostart has been configured: true
[2024-07-11 10:44:43.948] [info]  [App.Config] config.autostart has been configured: true
[2024-07-11 10:44:45.189] [warn]  [WebContentsEventM...] [Mattermost / ILS] [TAB_PLAYBOOKS] [renderer] Legacy preload initialized
[2024-07-11 10:44:45.561] [warn]  [WebContentsEventM...] [Mattermost / ILS] [TAB_MESSAGING] [renderer] Legacy preload initialized
[2024-07-11 10:44:47.368] [info]  [UpdateManager] Checking for update
[2024-07-11 10:44:48.582] [info]  [UpdateManager] Update for version 5.8.1 is not available (latest version: 5.8.1, downgrade is disallowed).
[2024-07-11 10:45:00.840] [error] Logger Log level set to: info
[2024-07-11 10:45:01.064] [info]  [App.Config] config.autostart has been configured: true
[2024-07-11 10:45:01.121] [info]  [App.Config] config.autostart has been configured: true
[2024-07-11 10:45:01.343] [error] [MainWindow] Error: Provided bounds info are outside the bounds of your screen, using defaults instead.
    at P.getSavedWindowState (C:\Users\xxx\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:802257)
    at P.init (C:\Users\xxx\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:798778)
    at P.show (C:\Users\xxx\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:800911)
    at C:\Users\xxx\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:212912
    at Vr (C:\Users\xxx\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:213635)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-07-11 10:45:01.432] [info]  [ServerDropdownView] init
[2024-07-11 10:45:01.500] [info]  [i18nManager] Set new language de
[2024-07-11 10:45:01.527] [info]  [App.Config] config.autostart has been configured: true
[2024-07-11 10:45:01.798] [info]  [App.Config] config.autostart has been configured: true
[2024-07-11 10:45:02.894] [info]  [App.Config] config.autostart has been configured: true
[2024-07-11 10:45:04.196] [warn]  [WebContentsEventM...] [Mattermost / ILS] [TAB_PLAYBOOKS] [renderer] Legacy preload initialized
[2024-07-11 10:45:04.403] [warn]  [WebContentsEventM...] [Mattermost / ILS] [TAB_MESSAGING] [renderer] Legacy preload initialized
[2024-07-11 10:45:06.339] [info]  [UpdateManager] Checking for update
[2024-07-11 10:45:07.797] [info]  [UpdateManager] Update for version 5.8.1 is not available (latest version: 5.8.1, downgrade is disallowed).
[2024-07-11 10:46:04.175] [error] [WebContentsEventM...] [Mattermost / ILS] [TAB_PLAYBOOKS] [renderer] Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
[2024-07-11 10:52:08.200] [error] [WebContentsEventM...] [Mattermost / ILS] [TAB_PLAYBOOKS] [renderer] Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
```

**Comment by jpk6789** [comment]
Oh I realized, that I named the wrong window mode. I actually meant the maximized mode of the window, where the title bar of the window is still visible. Then, as I said, I would expect, that I can move the window and the maximixed mode is switched to the normal window mode like it is usual under Windows. Sorry for this misconception.
