### ISSUE TITLE
[Bug]: Handelable exception thrown as runtime error. (Server selection)

### ISSUE THREAD

**Issue by fredx30** [mattermost/desktop#3122]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

Github "master" at time of writing

### Operating System

Windows_NT 10.0.19045 x64

### Mattermost Server Version

n/a

### Steps to reproduce

n/a - Dont know.

### Expected behavior

A working mattermost client with a servers list should not log uncaughtExceptions due to lack of current server.

### Observed behavior

"uncaughtExceptions" are logged to disk.

### Log Output

```shell
Application: Mattermost 5.8.1
Platform: Windows_NT 10.0.19045 x64
Error: No server set as current
    at Object.getCurrentServer (C:\Users\<win-username>\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:47496)
    at C:\Users\<win-username>\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:235771
    at Array.map (<anonymous>)
    at C:\Users\<win-username>\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:235605
    at C:\Users\<win-username>\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:237537
    at Te (C:\Users\<win-username>\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:237544)
    at C:\Users\<win-username>\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:213456
    at Vr (C:\Users\<win-username>\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:2:213635)
```

### Additional Information

Seems to originate here https://github.com/mattermost/desktop/blob/master/src/app/serverViewState.ts#L76
 
This bothers me somewhat. Either the reason for the log hit is not relevant to the reason as described in the text, or there is a bug in the code. I see no alternatives. 

Either way this is distracting me from searching for a real bug im more intrested in- report on that pending investigation.

**Comment by devinbinnie** [comment]
@fredx30 If this is something that you're seeing then it should probably be investigated as a potential bug.

There is a reason that we specifically don't handle this exception and that's that we don't expect this to happen. If it is happening however we want the app to be loud about it, meaning logging it and providing the information we need to solve it. We expect that if this occurs the app should hard reset and crash rather than try to figure out how to recover. If there is a specific way to handle this that we expect to happen, we can add that handler.

The stack trace above is helpful, so technically this should be a crash report. But we don't plan to stop logging these exceptions, as this case should never happen and we'd prefer to investigate and fix the issue.

Created a ticket for the crash here: [MM-60201](https://mattermost.atlassian.net/browse/MM-60201)
