### ISSUE TITLE
[Crash]: TypeError: s.nativeImage.createThumbnailFromPath is not a function

### ISSUE THREAD

**Issue by Caboose700** [mattermost/desktop#3129]
### Before you file a crash report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

Version 5.9.0

### Operating System

Debian 12.6

### Mattermost Server Version

9.4.1

### What type of crash did you experience?

Uncaught exception (I saw a dialog pop up that said "The Mattermost app quit unexpectedly")

### Crash report details

```shell
Application: Mattermost 5.9.0
Platform: Linux 6.9.7+bpo-amd64 x64
TypeError: s.nativeImage.createThumbnailFromPath is not a function
    at C.formatDownloadItem (/tmp/user/1000/.mount_matter8OQjCH/resources/app.asar/index.js:2:258218)
    at C.upsertFileToDownloads (/tmp/user/1000/.mount_matter8OQjCH/resources/app.asar/index.js:2:255626)
    at C.doneEventController (/tmp/user/1000/.mount_matter8OQjCH/resources/app.asar/index.js:2:256982)
    at DownloadItem.<anonymous> (/tmp/user/1000/.mount_matter8OQjCH/resources/app.asar/index.js:2:254788)
    at Object.onceWrapper (node:events:634:26)
    at DownloadItem.emit (node:events:519:28)
```

### Log Output

```shell
[2024-08-19 15:47:01.873] [error] Logger Log level set to: info
[2024-08-19 15:47:02.021] [warn]  [App.Initialize] Current working directory is /home/sabrina, changing into /tmp/user/1000/.mount_matterCxVGUC
[2024-08-19 15:47:02.252] [info]  [App.Config] config.autostart has been configured: false
[2024-08-19 15:47:02.615] [info]  [ServerDropdownView] init
[2024-08-19 15:47:02.759] [warn]  [i18nManager] Failed to set new language en-US
[2024-08-19 15:47:02.759] [warn]  [i18nManager] Failed to set new language US
[2024-08-19 15:47:03.013] [info]  [App.Config] config.autostart has been configured: false
[2024-08-19 15:47:03.709] [info]  [App.Config] config.autostart has been configured: false
[2024-08-19 15:47:07.479] [info]  [UpdateManager] Checking for update
[2024-08-19 15:47:07.669] [info]  [UpdateManager] Update for version 5.9.0 is not available (latest version: 5.9.0, downgrade is disallowed).
[2024-08-19 15:48:01.261] [error] Logger Log level set to: info
[2024-08-19 15:48:01.426] [warn]  [App.Initialize] Current working directory is /home/sabrina, changing into /tmp/user/1000/.mount_matterkNoXsz
[2024-08-19 15:48:01.655] [info]  [App.Config] config.autostart has been configured: false
[2024-08-19 15:48:01.888] [error] [MainWindow] Error: Provided bounds info are outside the bounds of your screen, using defaults instead.
    at P.getSavedWindowState (/tmp/user/1000/.mount_matterkNoXsz/resources/app.asar/index.js:2:819478)
    at P.init (/tmp/user/1000/.mount_matterkNoXsz/resources/app.asar/index.js:2:815824)
    at P.show (/tmp/user/1000/.mount_matterkNoXsz/resources/app.asar/index.js:2:818038)
    at /tmp/user/1000/.mount_matterkNoXsz/resources/app.asar/index.js:2:213809
    at zr (/tmp/user/1000/.mount_matterkNoXsz/resources/app.asar/index.js:2:214532)
```

### Additional Information

Crash occurred when hovering over an image, and clicking on the Download button.

**Comment by devinbinnie** [comment]
Thanks for catching this, yes this function is not available on Linux.
Created a ticket: https://mattermost.atlassian.net/browse/MM-60232

**Comment by BlackOpsDown** [comment]
Have the same issue on Fedora 40. Other than this Mattermost is perfect on Linux including screen sharing under Wayland.

**Comment by patrickmelix** [comment]
Can confirm this also affects the latest snap version under Ubuntu 24.04, same crash report (different paths for snap obviously). Is there a quick fix to use Mattermost Desktop productively again?
