### ISSUE TITLE
[Bug]: [macos-notification-state] failed to load 'notificationstate'

### ISSUE THREAD

**Issue by naveenyagati** [mattermost/desktop#3211]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.10.0

### Operating System

Kali GNU/Linux Rolling

### Mattermost Server Version

9.6.1

### Steps to reproduce

mattermost desktop app does not open anymore, I tried running mattermost-desktop on cmd and got the following error.

`13:21:54.778 › Logger Log level set to: info
[macos-notification-state] failed to load 'notificationstate' addon Error: Module did not self-register: '/opt/Mattermost/resources/app.asar.unpacked/node_modules/macos-notification-state/build/Release/notificationstate.node'.
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/opt/Mattermost/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at safeLoad (/opt/Mattermost/resources/app.asar/node_modules/macos-notification-state/lib/index.js:3:31) {
  code: 'ERR_DLOPEN_FAILED'
}
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
13:21:54.850 › [App.Initialize] Current working directory is /home/smallcase, changing into /opt/Mattermost
`

### Expected behavior

-

### Observed behavior

App wont open

### Log Output

```shell
13:21:54.778 › Logger Log level set to: info
[macos-notification-state] failed to load 'notificationstate' addon Error: Module did not self-register: '/opt/Mattermost/resources/app.asar.unpacked/node_modules/macos-notification-state/build/Release/notificationstate.node'.
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/opt/Mattermost/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at safeLoad (/opt/Mattermost/resources/app.asar/node_modules/macos-notification-state/lib/index.js:3:31) {
  code: 'ERR_DLOPEN_FAILED'
}
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
13:21:54.850 › [App.Initialize] Current working directory is /home/smallcase, changing into /opt/Mattermost
```

**Comment by felixhekhorn** [comment]
I can confirm this.

```
$ mattermost-desktop --version
12:50:43.896 › Logger Log level set to: info
[macos-notification-state] failed to load 'notificationstate' addon Error: Module did not self-register: '/opt/Mattermost/resources/app.asar.unpacked/node_modules/macos-notification-state/build/Release/notificationstate.node'.
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/opt/Mattermost/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at safeLoad (/opt/Mattermost/resources/app.asar/node_modules/macos-notification-state/lib/index.js:3:31) {
  code: 'ERR_DLOPEN_FAILED'
}
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
5.10.0
```
and also window would not open.

I have also a possibly related uncaught exception:
```
Application: Mattermost 5.10.0 [commit: 869aead
]
Platform: Linux 6.11.8-1-siduction-amd64 x64
Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:161:15)
    at writeGeneric (node:internal/stream_base_commons:152:3)
    at Socket._writeGeneric (node:net:954:11)
    at Socket._write (node:net:966:8)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at console.value (node:internal/console/constructor:310:16)
    at console.error (node:internal/console/constructor:394:26)
    at Function.writeFn (/opt/Mattermost/resources/app.asar/index.js:2:932907)
```
Let me also point out the "**macos**-notification-state" on a Linux system

**Comment by devinbinnie** [comment]
That `macos-notification-state` log entry is a red herring, and has been there since we started using the module (it doesn't load on Linux because it's not needed. I can load v5.10 on Ubuntu, with that message popping up in my log and the app loads and works correctly.

Is there any other information in the logs? Do you have AppArmor running? Are you trying to run as root?

**Comment by felixhekhorn** [comment]
> Is there any other information in the logs?

in `.config/Mattermost/logs/main.log` I have with yesterdays timestamp
```
[2024-11-19 12:22:25.608] [error] [WebContentsEventM...] [renderer] TypeError: Failed to fetch
[2024-11-19 12:22:25.639] [error] [WebContentsEventM...] [renderer] com.mattermost.calls: TypeError: Failed to fetch
[2024-11-19 12:35:40.641] [error] Logger Log level set to: info
[2024-11-19 12:35:40.761] [warn]  [App.Initialize] Current working directory is /home/felix, changing into /opt/Mattermost
[2024-11-19 12:35:40.856] [info]  [App.Config] config.autostart has been configured: true
[2024-11-19 12:35:40.925] [info]  [App.Initialize] Autoupgrade disabled: false
[2024-11-19 12:35:40.980] [info]  [ServerDropdownView] init
[2024-11-19 12:35:41.019] [info]  [i18nManager] Set new language de
[2024-11-19 12:35:41.209] [info]  [App.Config] config.autostart has been configured: true
[2024-11-19 12:35:43.024] [info]  [App.Config] config.autostart has been configured: true
[2024-11-19 15:49:35.864] [error] [WebContentsEventM...] [renderer] TypeError: Failed to fetch
[2024-11-19 15:49:35.908] [error] [WebContentsEventM...] [renderer] Uncaught (in promise) Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
```
is this what you are asking for?

However, the problem is already around for a couple of days for me and I don't remember since when exactly ... I was suspecting it was related to an update of my system packages.

> Do you have AppArmor running?

I'm using Debian unstable - so I think it is built into the kernel, no? (if I understood correctly - not sure)

> Are you trying to run as root?

no

> and the app loads and works correctly.

just to clarify: the app seems to run, i.e. `htop` shows it (and I can terminate it from there and launch it again and it appears back in the list), but the window does not pop-up

**Comment by felixhekhorn** [comment]
So the window is still there, but it seems there is a memory leak around:
```
(node:2370436) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added to [BrowserWindow]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `mattermost-desktop --trace-warnings ...` to show where the warning was created)
```

**Comment by devinbinnie** [comment]
> So the window is still there, but it seems there is a memory leak around:
> 
> ```
> (node:2370436) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added to [BrowserWindow]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
> (Use `mattermost-desktop --trace-warnings ...` to show where the warning was created)
> ```

This is also a red herring, this is a message from Node, we just add a lot of listeners to our Main Window object.

**Comment by felixhekhorn** [comment]
The issue seems to be solved for me with the upgrade to 5.10.1 (which came in a few weeks back)

**Comment by devinbinnie** [comment]
@naveenyagati Is this still an issue for you on v5.10.1 or v5.10.2?

**Comment by Arberesto** [comment]
Hi!

I have similar issue on Linux Mint 20, Cinnamon 4.6.7
Mattermost desktop, version 5.10.2


Installed Mattermost from apt, using official manual for Ubuntu/Debian: https://docs.mattermost.com/collaborate/install-desktop-app.html

Previously had manual install from tar.gz of lower version, but removed it prior to install
Next day, app crashes when trying to open it.

When I open app with `mattermost-desktop` command in terminal, here is the logs:

> 12:09:49.786 › Logger Log level set to: info
[macos-notification-state] failed to load 'notificationstate' addon Error: Module did not self-register: '/opt/Mattermost/resources/app.asar.unpacked/node_modules/macos-notification-state/build/Release/notificationstate.node'.
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/opt/Mattermost/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at safeLoad (/opt/Mattermost/resources/app.asar/node_modules/macos-notification-state/lib/index.js:3:31) {
  code: 'ERR_DLOPEN_FAILED'
}
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
12:09:49.995 › [App.Initialize] Current working directory is /home/username, changing into /opt/Mattermost
12:09:50.113 › [App.Config] config.autostart has been configured: true
INTEL-MESA: warning: Haswell Vulkan support is incomplete
12:09:50.212 › [App.Initialize] Autoupgrade disabled: false
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
12:09:50.312 › [ServerDropdownView] init
12:09:50.378 › [i18nManager] Failed to set new language en-US
12:09:50.379 › [i18nManager] Failed to set new language US
12:09:50.561 › [App.Config] config.autostart has been configured: true
12:09:50.644 › [WebContentsEventM...] [renderer] Error with Permissions-Policy header: Parse of permissions policy failed because of errors reported by structured header parser.
12:09:51.886 › [App.Config] config.autostart has been configured: true
Trace/breakpoint trap (core dumped)


Checking `/opt/Mattermost`, I see that owner of folder and everything inside it is `root` user, not my user. But I assume that is normal. Changing it with `chown` to my user doesn't resolve the issue, so I rolled it back.

And there are files in `/opt/Mattermost` with date of Dec 17, which was before I installed new version. Not sure if they from last installation or not.

**Comment by lkraav** [comment]
Linux 5.11.2: I also found one of my client machines start running into this out of the blue.

Disabling hardware acceleration from Settings seems to have helped, thanks for this tip - would've never thought to look into that direction based on topic error message. Does anyone here know yet, why aren't we failing with a more clear error output?

Looking at the system logs, I'm seeing us failing to initialize Vulkan but it's a bit unclear right now why it seemingly suddenly triggered on this system

```
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883756]: [1883756:0421/233132.529410:ERROR:browser_main_loop.cc(278)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed                
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.592913:ERROR:angle_platform_impl.cc(44)] vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_EXT_headless_su
rface                                                                                                                                                                                                                                         
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: ERR: vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_EXT_headless_surface                                                    
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.593028:ERROR:angle_platform_impl.cc(44)] vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_KHR_surface    
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: ERR: vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_KHR_surface                                                             
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.593091:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-
7): A requested extension is not supported, in ../../third_party/angle/src/libANGLE/renderer/vulkan/vk_renderer.cpp, enableInstanceExtensions:2035.                                                                                           
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-7): A requested extension is not supported, in ../../thir
d_party/angle/src/libANGLE/renderer/vulkan/vk_renderer.cpp, enableInstanceExtensions:2035.                                                                                                                                                    
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.593163:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Internal Vulkan error (-7): A requested extension is 
not supported, in ../../third_party/angle/src/libANGLE/renderer/vulkan/vk_renderer.cpp, enableInstanceExtensions:2035.                                                                                                                        apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.593214:ERROR:gl_display.cc(762)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.593266:ERROR:gl_display.cc(796)] Initialization of all EGL display types failed.                                                   apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.593315:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.                                                 
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.609552:ERROR:angle_platform_impl.cc(44)] vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_EXT_headless_surface                                                                                                                                                                                                                                         
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: ERR: vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_EXT_headless_surface                       
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.609685:ERROR:angle_platform_impl.cc(44)] vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_KHR_surface    
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: ERR: vk_renderer.cpp:181 (VerifyExtensionsPresent): Extension not supported: VK_KHR_surface                                                             
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.609765:ERROR:angle_platform_impl.cc(44)] Display.cpp:1056 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-
7): A requested extension is not supported, in ../../third_party/angle/src/libANGLE/renderer/vulkan/vk_renderer.cpp, enableInstanceExtensions:2035.                                                                                      
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: ERR: Display.cpp:1056 (initialize): ANGLE Display::initialize error 0: Internal Vulkan error (-7): A requested extension is not supported, in ../../thir
d_party/angle/src/libANGLE/renderer/vulkan/vk_renderer.cpp, enableInstanceExtensions:2035.                                                                                                                                                    
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.609829:ERROR:gl_display.cc(493)] EGL Driver message (Critical) eglInitialize: Internal Vulkan error (-7): A requested extension is 
not supported, in ../../third_party/angle/src/libANGLE/renderer/vulkan/vk_renderer.cpp, enableInstanceExtensions:2035.                                                                                                                        apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.609875:ERROR:gl_display.cc(762)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED                                       
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.609921:ERROR:gl_display.cc(796)] Initialization of all EGL display types failed.                                                   apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.609964:ERROR:gl_ozone_egl.cc(26)] GLDisplayEGL::Initialize failed.                                                 
apr   21 23:31:32 avocado mattermost-desktop-mattermost-desktop-bin.desktop[1883866]: [1883866:0421/233132.615039:ERROR:viz_main_impl.cc(185)] Exiting GPU process due to errors during initialization                                        
```

**Comment by devinbinnie** [comment]
The loading issue is happening at the Electron/Node level - which our app doesn't have control over. So I wouldn't be able to catch this error consistently, since often when it happens it's just because you're not on macOS. You'll notice many of those messages include .cpp extensions, which means it's failing to load the C++ module here, nothing within JavaScript.

**Comment by w-poh** [comment]
I encounter similar problems when I launched mattermost-desktop the first time. 
I installed mattermost via the official guide [install guide](https://docs.mattermost.com/collaborate/install-desktop-app.html), `sudo apt install mattermost-desktop` and used the latest firefox to allow the connection through my institution's gitlab. 

mattermost-desktop --version : 5.12.1
firefox --version : Mozilla Firefox 140.0.2

My error logs read:
`
07:20:07.282 › Logger Log level set to: info
[macos-notification-state] failed to load 'notificationstate' addon Error: Module did not self-register: '/opt/Mattermost/resources/app.asar.unpacked/node_modules/macos-notification-state/build/Release/notificationstate.node'.
    at process.func [as dlopen] (node:electron/js2c/node_init.....
    at Module._extensions..node (node:internal/modules/cjs/loader....
    at Object.func [as .node] (node:electron/js2c/node_init....
    at Module.load (node:internal/modules/cjs/loader....
    at Module._load (node:internal/modules/cjs/loader.....
    at c._load (node:electron/js2c/node_init.....
    at TracingChannel.traceSync (node:diagnostics_channel.....
    at wrapModuleLoad (node:internal/modules/cjs/loader.....
    at Module.require (node:internal/modules/cjs/loader....
    at require (node:internal/modules/helpers.... {
  code: 'ERR_DLOPEN_FAILED'
}
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
07:20:07.370 › [App.Initialize] Current working directory is XXX, changing into /opt/Mattermost
07:20:07.450 › [App.Config] config.autostart has been configured: false
07:20:07.502 › [App.Initialize] Autoupgrade disabled: false
07:20:07.546 › [ServerDropdownView] init
07:20:07.578 › [i18nManager] Failed to set new language en-US
07:20:07.579 › [i18nManager] Failed to set new language US
07:20:07.764 › [App.Config] config.autostart has been configured: false
07:20:07.997 › [App.Config] config.autostart has been configured: false
07:20:08.495 › [WebContentsEventM...] [renderer] Uncaught (in promise) Error: Not authorized

With online help (also through LLMs) it did not work out, so I tried a simple solution: copy the allowing link that's opened by the desktop app in Chromium (--version: 138.0.7204.49 snap) and authorized mattermost there. Worked directly!
