### ISSUE TITLE
[Bug]: starting another mattermost-desktop command does not bring app to forground any more with 5.10

### ISSUE THREAD

**Issue by errror** [mattermost/desktop#3213]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.10.0

### Operating System

Debian 12

### Mattermost Server Version

9.11.1

### Steps to reproduce

1. Start the mattermost-desktop app, either via autostart on login or manual, either minimized or not.
2. Minimize (if not) the app window to notification area by pressing Ctrl-w
3. Reopen the app window by running the mattermost-desktop command, either on cmdline or application launcher or self-defined keyboard shortcut.

### Expected behavior

The app window opens and the (second) mattermost-desktop command terminates successfully. This was the behaviour until 5.10.0.

### Observed behavior

The app window does not show up, the (second) mattermost-desktop command only exits. This behavior started with 5.10.0.

### Log Output

```shell
First command:

13:40:32.351 › Logger Log level set to: info
[macos-notification-state] failed to load 'notificationstate' addon Error: Module did not self-register: '/opt/Mattermost/resources/app.asar.unpacked/node_modules/macos-notification-state/build/Release/notificationstate.node'.
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/opt/Mattermost/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at safeLoad (/opt/Mattermost/resources/app.asar/node_modules/macos-notification-state/lib/index.js:3:31) {
  code: 'ERR_DLOPEN_FAILED'
}
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
13:40:32.633 › [App.Initialize] Current working directory is /home/XXXXXXXX, changing into /opt/Mattermost
13:40:34.528 › [App.Config] config.autostart has been configured: true
13:40:34.550 › [App.Initialize] Autoupgrade disabled: false
13:40:34.604 › [ServerDropdownView] init
13:40:34.665 › [i18nManager] Set new language de
13:40:34.821 › [App.Config] config.autostart has been configured: true
13:40:35.517 › [App.Config] config.autostart has been configured: true
13:40:36.906 › [WebContentsEventM...] [renderer] Uncaught (in promise) Error: Ungültiger oder fehlender user_id Parameter in Anfrage-URL.

Second command:
13:42:25.938 › Logger Log level set to: info
[macos-notification-state] failed to load 'notificationstate' addon Error: Module did not self-register: '/opt/Mattermost/resources/app.asar.unpacked/node_modules/macos-notification-state/build/Release/notificationstate.node'.
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/opt/Mattermost/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at safeLoad (/opt/Mattermost/resources/app.asar/node_modules/macos-notification-state/lib/index.js:3:31) {
  code: 'ERR_DLOPEN_FAILED'
}
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
13:42:26.051 › [App.Initialize] Current working directory is /home/XXXXXXXX, changing into /opt/Mattermost
```

### Additional Information

For years now, I used a KDE keyboard shortcut that invokes the `mattermost-desktop` command. If the app was not running, it was started (according to my setting minimized to notification area), otherwise the app windows opened and got the focus. If there is another way, to tell the running mattermost-desktop client instance to open the main window and grab the focus - by a shell command or KDE global keyboard shortcut - please let me know!

**Comment by devinbinnie** [comment]
Verified, created a ticket: https://mattermost.atlassian.net/browse/MM-61864

**Comment by errror** [comment]
Just tested 5.10.1: fixes the issue.

Thanks for the quick update!
