### ISSUE TITLE
[Bug]: In Ubuntu 24.04, the icon does not appear in the app bar.

### ISSUE THREAD

**Issue by jclab-joseph** [mattermost/desktop#3219]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.10.1

### Operating System

Ubuntu 24.04 LTS x64

### Mattermost Server Version

8.1.13

### Steps to reproduce

![image](https://github.com/user-attachments/assets/25941be7-f490-4bf6-b8c7-03e22876c3c4)

![image](https://github.com/user-attachments/assets/e3e61021-fa4a-4231-8fde-587b16e5ee35)

### Expected behavior

should see the mattermost icon instead of the settings icon.

### Observed behavior

See the screenshot.

### Log Output

```shell
[2024-11-22 11:11:22.849] [error] Logger Log level set to: info
[2024-11-22 11:11:23.056] [info]  [App.Config] config.autostart has been configured: true
[2024-11-22 11:11:23.110] [info]  [App.Initialize] Autoupgrade disabled: false
[2024-11-22 11:11:23.110] [error] [MainWindow] Error: Provided bounds info are outside the bounds of your screen, using defaults instead.
    at P.getSavedWindowState (/home/user/.programs/mattermost-desktop-5.10.1-linux-x64/resources/app.asar/index.js:2:877924)
    at P.init (/home/user/.programs/mattermost-desktop-5.10.1-linux-x64/resources/app.asar/index.js:2:874269)
    at P.show (/home/user/.programs/mattermost-desktop-5.10.1-linux-x64/resources/app.asar/index.js:2:876409)
    at /home/user/.programs/mattermost-desktop-5.10.1-linux-x64/resources/app.asar/index.js:2:215792
    at Vr (/home/user/.programs/mattermost-desktop-5.10.1-linux-x64/resources/app.asar/index.js:2:216533)
[2024-11-22 11:11:23.158] [info]  [ServerDropdownView] init
[2024-11-22 11:11:23.177] [info]  [i18nManager] Set new language ko
[2024-11-22 11:11:23.303] [info]  [App.Config] config.autostart has been configured: true
[2024-11-22 11:11:23.639] [info]  [App.Config] config.autostart has been configured: true
[2024-11-22 11:11:24.674] [warn]  [WebContentsEventM...] [renderer] Legacy preload initialized
```
```


### Additional Information

_No response_

**Comment by devinbinnie** [comment]
This looks like an issue with the `.desktop` file, as I believe it contains the icon information. How did you install Mattermost on your system?

**Comment by jclab-joseph** [comment]
I downloaded and unpacked the tar archive.
Can I regenerate the desktop file? The app icon path is correct.

**Comment by jclab-joseph** [comment]
It was created as below, and even when I run it, the icon does not appear.

```
[Desktop Entry]
Name=Mattermost
Comment=Mattermost Desktop application for Linux
Exec="/home/USER/.programs/mattermost-desktop-5.10.1-linux-x64/mattermost-desktop" %U
Terminal=false
Type=Application
MimeType=x-scheme-handler/mattermost
Icon=/home/USER/.programs/mattermost-desktop-5.10.1-linux-x64/app_icon.png
Categories=Network;InstantMessaging;
```


![image](https://github.com/user-attachments/assets/51627470-36fd-4c3b-867c-eba233140c9d)
![image](https://github.com/user-attachments/assets/e4bdc572-1d8d-4558-a206-df4efb752a64)

**Comment by devinbinnie** [comment]
I can't reproduce this I'm afraid, perhaps try restarting your session or remaking the `.desktop` file. Which window manager are you using? I was able to get it working with default GNOME

**Comment by devinbinnie** [comment]
Closing as inactive.
