### ISSUE TITLE
[Crash]: failed to load 'notificationstate' addon Error: Module did not self-register

### ISSUE THREAD

**Issue by morten-b** [mattermost/desktop#3261]
### Before you file a crash report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.9.0

### Operating System

NixOS 24.11

### Mattermost Server Version

9.11.1

### What type of crash did you experience?

System crash (The application quit unexpectedly with no warning, or the operating system reported a crash)

### Crash report details

```shell
morten@nixos ~> mattermost-desktop
08:28:30.548 › Logger Log level set to: info
[macos-notification-state] failed to load 'notificationstate' addon Error: Module did not self-register: '/nix/store/bgkwklisjrddx6svc9crz7a27pav45kb-mattermost-desktop-5.9.0/share/mattermost-desktop/app.asar.unpacked/node_modules/macos-notification-state/build/Release/notificationstate.node'.
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/nix/store/bgkwklisjrddx6svc9crz7a27pav45kb-mattermost-desktop-5.9.0/share/mattermost-desktop/app.asar/node_modules/bindings/bindings.js:112:48)
    at safeLoad (/nix/store/bgkwklisjrddx6svc9crz7a27pav45kb-mattermost-desktop-5.9.0/share/mattermost-desktop/app.asar/node_modules/macos-notification-state/lib/index.js:3:31) {
  code: 'ERR_DLOPEN_FAILED'
}
08:28:30.627 › [App.Initialize] Current working directory is /home/morten, changing into /nix/store/rcvns6kf38zddhxq7q05msnjbyz8gmzd-electron-unwrapped-33.3.0/libexec/electron
08:28:30.697 › [App.Config] config.autostart has been configured: true
08:28:30.709 › [App.Initialize] Autoupgrade disabled: false
08:28:30.730 › [ServerDropdownView] init
08:28:30.751 › [i18nManager] Failed to set new language en-GB
08:28:30.751 › [i18nManager] Failed to set new language DK
08:28:30.863 › [App.Config] config.autostart has been configured: true
08:28:31.407 › [App.Config] config.autostart has been configured: true
(electron) 'webContents.clearHistory' is deprecated and will be removed. Please use 'webContents.navigationHistory.clear' instead.
(electron) 'webContents.canGoBack' is deprecated and will be removed. Please use 'webContents.navigationHistory.canGoBack' instead.
(electron) 'webContents.canGoForward' is deprecated and will be removed. Please use 'webContents.navigationHistory.canGoForward' instead.
[35842:1220/082906.311295:ERROR:wayland_event_watcher.cc(47)] libwayland: zxdg_exporter_v2#25: error 0: exported surface had an invalid role

fish: Job 1, 'mattermost-desktop' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

### Log Output

```shell
[2024-12-20 08:27:10.924] [error] Logger Log level set to: info
[2024-12-20 08:27:11.004] [warn]  [App.Initialize] Current working directory is /home/morten, changing into /nix/store/rcvns6kf38zddhxq7q05msnjbyz8gmzd-electron-unwrapped-33.3.0/libexec/electron
[2024-12-20 08:27:11.066] [info]  [App.Config] config.autostart has been configured: true
[2024-12-20 08:27:11.075] [info]  [App.Initialize] Autoupgrade disabled: false
[2024-12-20 08:27:11.076] [error] [MainWindow] Error: Provided bounds info are outside the bounds of your screen, using defaults instead.
    at P.getSavedWindowState (/nix/store/bgkwklisjrddx6svc9crz7a27pav45kb-mattermost-desktop-5.9.0/share/mattermost-desktop/app.asar/index.js:2:819478)
    at P.init (/nix/store/bgkwklisjrddx6svc9crz7a27pav45kb-mattermost-desktop-5.9.0/share/mattermost-desktop/app.asar/index.js:2:815824)
    at P.show (/nix/store/bgkwklisjrddx6svc9crz7a27pav45kb-mattermost-desktop-5.9.0/share/mattermost-desktop/app.asar/index.js:2:818038)
    at /nix/store/bgkwklisjrddx6svc9crz7a27pav45kb-mattermost-desktop-5.9.0/share/mattermost-desktop/app.asar/index.js:2:213809
    at zr (/nix/store/bgkwklisjrddx6svc9crz7a27pav45kb-mattermost-desktop-5.9.0/share/mattermost-desktop/app.asar/index.js:2:214532)
[2024-12-20 08:27:11.099] [info]  [ServerDropdownView] init
[2024-12-20 08:27:11.121] [warn]  [i18nManager] Failed to set new language en-GB
[2024-12-20 08:27:11.121] [warn]  [i18nManager] Failed to set new language DK
[2024-12-20 08:27:11.228] [info]  [App.Config] config.autostart has been configured: true
[2024-12-20 08:27:11.779] [info]  [App.Config] config.autostart has been configured: true
```

### Additional Information

App crashes when app is closed, but only when `Leave app running in notification area when application window is closed` is set

**Comment by morten-b** [comment]
As #3211 but being provoked but other events

**Comment by devinbinnie** [comment]
Closing this one in favour of #3211, as it is likely the same issue. FWIW this is likely an OS issue not an app issue, most distributions don't run into this. Likely something with permissions, but nothing has been reproduced yet.
